### ISSUE TITLE
Two entities pointing to same trope are not visualized

### ISSUE THREAD

**Issue by blcham** [datagov-cz/ontoGrapher#218]
In model částky, two entities are pointing to the same trope with the same cardinalities. OntoGrapher  does not visualize any connection to the trope.

Diagram of model in modelio:
![image](https://user-images.githubusercontent.com/3962237/106048981-de66fa00-60e5-11eb-96ad-4696c5687a61.png)

Same diagram in ontoGrapher:
![Selection_357](https://user-images.githubusercontent.com/3962237/106049140-18d09700-60e6-11eb-8320-50809f706c15.jpg)

Relevant ttl file:

[g-sgov-částky-model.ttl.gz](https://github.com/opendata-mvcr/ontoGrapher/files/5882820/g-sgov-castky-model.ttl.gz)

**Comment by bindeali** [comment]
Closing as stale.
