### ISSUE TITLE
Exported data contain conflicting types

### ISSUE THREAD

**Issue by psiotwo** [datagov-cz/ontoGrapher#260]
see https://github.com/opendata-mvcr/ssp/pull/264/files

There is the following snippet showing kapacita as both a owl: DatatypeProperty, and  z-sgov-pojem:typ-vztahu. Also  rdfs:subClassOf z-sgov-pojem:vlastnost is in conflict with z-sgov-pojem:typ-vztahu.

Maybe not an issue of OG, just an artifact of wrong input data.
---

d-sgov-turistické-cíle-pojem:kapacita a owl:Class, owl:DatatypeProperty, z-sgov-pojem:typ-vztahu;
  rdfs:domain d-sgov-turistické-cíle-pojem:turistický-cíl;
  rdfs:range rdfs:Literal;
  rdfs:subClassOf z-sgov-pojem:vlastnost, [ a owl:Restriction;
      owl:minQualifiedCardinality "1"^^xsd:nonNegativeInteger;
      owl:onClass d-sgov-turistické-cíle-pojem:turistický-cíl;
      owl:onProperty z-sgov-pojem:má-vztažený-prvek-1
    ]

**Comment by bindeali** [comment]
The way it _should_ (barring any bugs) work in OG is that any types not modifiable by the UI (as in those available in the detail panel) are kept in each update. OG keeps track of all types the term has and only modifies the aforementioned ones. Given the fact that other problems with types [have been reported](https://github.com/opendata-mvcr/ontoGrapher/issues/256) recently, I think it warrants further investigation on my part - will report back later.

**Comment by bindeali** [comment]
Closing as this fixed. The linked issue has been closed already and the saving logic does not modify other types.
