### ISSUE TITLE
R/O vocabulary with all elements hidden might hide again

### ISSUE THREAD

**Issue by psiotwo** [datagov-cz/ontoGrapher#267]
![image](https://user-images.githubusercontent.com/1140626/117147321-6e87a000-adb5-11eb-9f4a-7b9e28bbddde.png)

This happen when I search a term in the cache, add it to the pane and hide it. Now, I don't have any term from a R/O vocabulary user and thus I don't need to see such vocabulary any more, otherwise the number of vocabularies will only increase in the list.

**Comment by bindeali** [comment]
Closing as this is resolved in PR https://github.com/datagov-cz/ontoGrapher/pull/519
