### ISSUE TITLE
English labels not stored

### ISSUE THREAD

**Issue by martinnec** [datagov-cz/ontoGrapher#303]
Workspace : https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance398749321

For example, in 

![image](https://user-images.githubusercontent.com/4235208/129245323-26435ee3-07ab-4b0a-85d9-2c28eee8fc06.png)

Object type "Registrace" - I fill in the czech and english description. When I reopen the worspace again, I can see only the czech description, not english description.

The behavior does not seem deterministic. For example, "Osvědčení o registraci" in the same diagram has both descriptions.

**Comment by martinnec** [comment]
It seems there are problems with storing even czech descriptions. I do not understand the logic of storing the descriptions. Sometimes it is stored, sometimes not.

**Comment by martinnec** [comment]
I think, this can be closed. It works correctly as intended probably. However, I thing that the intention needs to be changed. See the new issue #368 .

**Comment by bindeali** [comment]
Closing as #368 is also closed.
