### ISSUE TITLE
Dragging a property on canvas does not work

### ISSUE THREAD

**Issue by psiotwo** [datagov-cz/ontoGrapher#311]
workspace: https://xn--slovnk-7va.gov.cz/modelujeme/v-n%C3%A1stroji/ontographer/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-538663409

Dragging "Identifikátor veřejné zakázky v elektronickém systému" into the Canvas does not work
![image](https://user-images.githubusercontent.com/1140626/132667016-1af6f015-58e9-43ca-8b78-f0ae031393cb.png)

**Comment by bindeali** [comment]
Closing this as no example of this issue has been reported recently.
