### ISSUE TITLE
Support for publishing diagrams alongside vocabularies (Milestone 1a)

### ISSUE THREAD

**Issue by karelklima** [datagov-cz/ontoGrapher#330]
We would like to persist diagrams created by OntoGrapher across multiple workspaces / vocabulary editing sessions so that users may publish a vocabulary with the diagrams and edit it afterwards if necessary.

In order to do that we need to adjust OntoGrapher data architecture regarding diagrams so that it can be understood by other components in the Assembly Line.

What exactly needs to be done:

1. OntoGrapher should save diagrams to a special asset GraphDB contexts that will be workspace specific. Each diagram will be stored in a separate context.
2. OntoGrapher should save metainformation that may be related to diagrams or other parts of the app to a special application DB context that will be also workspace specific. There may be only one such context per workspace.
3. OntoGrapher should not create any other contexts in the database, except the two types mentioned above.

The contexts must adhere to the workspace data architecture specification. The revised version is available here: https://docs.google.com/document/d/1NAwSgQGoOhnFcQ-oko5Rf6lgOYV5BVSpu1nAaEP1ZlQ/edit#heading=h.325e28y8myej

**Comment by psiotwo** [comment]
@bindeali can we close this one?

**Comment by bindeali** [comment]
Closing as this has been long resolved.
