### ISSUE TITLE
Published diagram not loaded to a new workspace

### ISSUE THREAD

**Issue by martinnec** [datagov-cz/ontoGrapher#374]
I created this new workspace:

https://slovník.gov.cz/modelujeme/workspace/instance57553275

No diagram was loaded even though it exists.

**Comment by martinnec** [comment]
https://xn--slovnk-7va.gov.cz/modelujeme/workspace/instance-529795838 - here it works correctly.

**Comment by bindeali** [comment]
Closing as these workspaces no longer exist; therefore I cannot verify the bug.
